language: cpp

compiler:
  - gcc
  - clang

cache: apt

sudo: false

addons:
  apt:
    packages:
    - libsqlite3-dev

script:
  - make -kj
  - make install run
  - wget -t 5 -T 1 --retry-connrefused http://127.7.7.7:8080/
  - cat index.html

branches:
  only:
    - beta
    - develop
    - master

notifications:
  email: false

matrix:
  fast_finish: true
